version: '4'

services:
  database:
    container_name: brida_shower_db
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123
volumes:
  postgres: