spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    platform: postgres
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
      database: postgresql