name: Build

on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'coretto'
          java-version: 21

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: GabrielGrabski/bridal-shower-api:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: GabrielGrabski/bridal-shower-api:latest